import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
// app/layout.tsx (Next.js 13/14 layout file)
// import Providers from "./providers";
import { ReactNode } from "react";
import Link from "next/link";
// import Header from "@/components/Header";
// import { ThemeToggle } from "@/components/ThemeToggle";
// import { AuthProvider } from "@/lib/auth-context";
// import ClientProvider from "./ClientProvider";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Boodschappenlijst",
//   description: "Laravel + Next.js boodschappen app",
// };

export function NavItem({
  label,
  href,
  children,
  // className,
}: {
  children: ReactNode;
  href: string;
  label?: string;
  className?: string;
}) {
  return (
    <Link href={href} className="flex flex-col items-center text-sm">
      <span className="text-2xl">{children}</span>
      {label && <span>{label}</span>}
    </Link>
  );
}

// export default function RootLayout({ children }: { children: ReactNode }) {
//   return (
//     <html lang="nl">
//       <body className="flex flex-col min-h-screen">
//         {/* Header met logo en zoekbalk */}
//         <header className="m-4 p-2 rounded bg-gray-500 shadow-md flex justify-between items-center">
//           <div className="text-xl font-bold">Logo</div>
//           {/* <input
//             type="text"
//             placeholder="Search for product..."
//             className="border p-2 rounded-md w-full max-w-md ml-4"
//           /> */}
//           <button className="cursor-pointer p-2">
//             <Settings className="w-6 h-6" />
//           </button>
//         </header>

//         {/* Main content */}
//         <main className="flex-grow">{children}</main>

//         {/* Bottom navigation bar */}
//         <footer className="bg-gray-500 p-4 flex justify-around border-t">
//           <NavItem label="Home">
//             <House />
//           </NavItem>
//           <NavItem label="Zoek">
//             <Search />
//           </NavItem>
//           <NavItem label="Boodschappenlijst">
//             <ShoppingCart />
//           </NavItem>
//           <NavItem label="Favorieten">
//             <Heart />
//           </NavItem>
//           <NavItem label="Profiel">
//             <User />
//           </NavItem>
//         </footer>
//       </body>
//     </html>
//   );
// }

// // import type { Metadata } from "next";
// // import { Geist, Geist_Mono } from "next/font/google";
// // import "./globals.css";

// // const geistSans = Geist({
// //   variable: "--font-geist-sans",
// //   subsets: ["latin"],
// // });

// // const geistMono = Geist_Mono({
// //   variable: "--font-geist-mono",
// //   subsets: ["latin"],
// // });

// // export const metadata: Metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// // export default function RootLayout({
// //   children,
// // }: Readonly<{
// //   children: React.ReactNode;
// // }>) {
// //   return (
// //     <html lang="en">
// //       <body
// //         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
// //       >
// //         {children}
// //       </body>
// //     </html>
// //   );
// // }

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="nl" suppressHydrationWarning>
      <body className={`${inter.className} flex flex-col min-h-screen bg-white text-gray-900 transition-colors overflow-y-scrollbar-none`}>
        <Providers>
          <div className="flex flex-col flex-grow">
            <div className="pt-16 pb-16">
              {children}
            </div>
          </div>
          <ToastContainer
            position="top-center"
            autoClose={3000}
            hideProgressBar={false}
            newestOnTop
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="light"
          />
        </Providers>
      </body>
    </html>
  );
}
